### ISSUE TITLE
AttributeError: 'module' object has no attribute 'load_data_1char'

### ISSUE THREAD

**Issue by sumarouno** [JackonYang/captcha-tensorflow#3]
I try your code, but encounter an error while execute softmax_with_log.py. any help?
thanks
```
[sumarsono@mesin-arch captcha-tensorflow]$ python2 softmax_with_log.py 
Traceback (most recent call last):
  File "softmax_with_log.py", line 115, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/sumarsono/captcha-tensorflow/virt/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "softmax_with_log.py", line 37, in main
    train_data, test_data = input_data.load_data_1char(FLAGS.data_dir)
AttributeError: 'module' object has no attribute 'load_data_1char'
```

**Comment by JackonYang** [comment]
fixed
